
package sms;


import java.io.FileNotFoundException;
import java.util.Formatter;
import javax.swing.JOptionPane;

/**
 *
 * @author AAHROI
 */
public class EditStudent extends javax.swing.JFrame {
    StudentManagementSystem sms ;
    Student std ;
    /**
     * Creates new form AddStudent
     */
    public EditStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        lblRN = new javax.swing.JLabel();
        txtRN = new javax.swing.JTextField();
        lblSN = new javax.swing.JLabel();
        txtSN = new javax.swing.JTextField();
        lblPN = new javax.swing.JLabel();
        txtPN = new javax.swing.JTextField();
        lblADR = new javax.swing.JLabel();
        txtADR = new javax.swing.JTextField();
        lblSG = new javax.swing.JLabel();
        txtSG = new javax.swing.JTextField();
        lblSG1 = new javax.swing.JLabel();
        txtSE = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        errName = new javax.swing.JLabel();
        errEmail = new javax.swing.JLabel();
        errGrade = new javax.swing.JLabel();
        errPhone = new javax.swing.JLabel();
        errAdr = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        bnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Student information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnEdit.setText("Search");
        btnEdit.setPreferredSize(new java.awt.Dimension(75, 25));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lblRN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRN.setText("Roll Number");

        txtRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRNActionPerformed(evt);
            }
        });

        lblSN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSN.setText("Name");

        txtSN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSNFocusLost(evt);
            }
        });
        txtSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSNActionPerformed(evt);
            }
        });

        lblPN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPN.setText("Phone Number");

        txtPN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPNFocusLost(evt);
            }
        });
        txtPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPNActionPerformed(evt);
            }
        });

        lblADR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblADR.setText("Address");

        txtADR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtADRFocusLost(evt);
            }
        });
        txtADR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtADRActionPerformed(evt);
            }
        });

        lblSG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSG.setText("Grade");

        txtSG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSGFocusLost(evt);
            }
        });
        txtSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSGActionPerformed(evt);
            }
        });

        lblSG1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSG1.setText("Email");

        txtSE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSEFocusLost(evt);
            }
        });
        txtSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSEActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.setPreferredSize(new java.awt.Dimension(75, 25));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        errName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errName.setForeground(new java.awt.Color(204, 0, 51));
        errName.setToolTipText("");

        errEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errEmail.setForeground(new java.awt.Color(204, 0, 51));
        errEmail.setToolTipText("");

        errGrade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errGrade.setForeground(new java.awt.Color(204, 0, 51));
        errGrade.setToolTipText("");

        errPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errPhone.setForeground(new java.awt.Color(204, 0, 51));
        errPhone.setToolTipText("");

        errAdr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errAdr.setForeground(new java.awt.Color(204, 0, 51));
        errAdr.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblRN, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPN, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addComponent(lblSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblADR, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPN, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtADR, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSN, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errName, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRN, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSG, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSE, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(errGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSN)
                            .addComponent(errName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSG)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(errGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSG1)
                    .addComponent(errEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblADR)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtADR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        lblInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(0, 0, 255));
        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo.setText("Thanks for using our services.");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        bnExit.setText("Exit");
        bnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Management System");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Update Student ");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(85, 85, 85)
                            .addComponent(btnLogout)
                            .addGap(87, 87, 87)
                            .addComponent(btnClose)
                            .addGap(103, 103, 103)
                            .addComponent(bnExit))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(btnClose)
                    .addComponent(bnExit))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if(txtRN.getText().isBlank()|| !txtRN.getText().matches("\\d+"))
        {
            this.lblInfo.setText("Invalid Roll Number.");
        }
        else
        {
            for (Student st : sms.getStudentList()) {
                if (st.getRollnumber() == Integer.parseInt(txtRN.getText())) {
                    lblInfo.setText("Student found with succes.");
                    txtSN.setText(st.getName());
                    txtPN.setText(st.getPhone());
                    txtSE.setText(st.getEmail());
                    txtSG.setText(st.getGrade()+"");
                    txtADR.setText(st.getAdr());
                    std = st;
                    btnUpdate.setEnabled(true);
                    //txtRN.requestFocus();
                    return;
                }
            }
            this.lblInfo.setText("Student Not found.");
            txtSN.setText("");
            txtPN.setText("");
            txtSE.setText("");
            txtSG.setText("");
            txtADR.setText("");
        }
    
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRNActionPerformed

    private void txtSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSNActionPerformed

    private void txtPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPNActionPerformed

    private void txtADRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtADRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtADRActionPerformed

    private void txtSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSGActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void bnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bnExitActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        new MainWindow().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        sms = new StudentManagementSystem();

        //sms.displayAllStudent();
   
        txtRN.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void txtSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSEActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(validInput()){
                
            btnUpdate.setEnabled(false);
            sms.removeStudent(std.getRollnumber());
            std.setName(txtSN.getText());
            std.setGrade(Double.parseDouble(txtSG.getText()));
            std.setEmail(txtSE.getText());
            std.setPhone(txtPN.getText());
            std.setAdr(txtADR.getText());
            sms.addStudent(std);

            Formatter f;
            try {
                f = new Formatter("d:\\SMS\\students.txt");
                 for(Student st:sms.getStudentList()){
                    f.format("%d,%s,%.2f,%s,%s,%s\r\n", 
                        st.getRollnumber(),st.getName(),
                        st.getGrade(),st.getEmail(),
                        st.getPhone(),st.getAdr());
                }

                f.close(); 
            } catch (FileNotFoundException ex) {
                 JOptionPane.showMessageDialog(null,"*File Error!* :"+ex.getLocalizedMessage());
            }
            this.lblInfo.setText("Student Updated.");
            txtSN.setText("");
            txtPN.setText("");
            txtSE.setText("");
            txtSG.setText("");
            txtADR.setText("");
            txtRN.setText(""); 
            txtRN.requestFocus();
        }
            
           
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        System.out.println("exit");
    }//GEN-LAST:event_formWindowClosed

    private void txtSNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSNFocusLost
        // TODO add your handling code here:
        validInput();
        
    }//GEN-LAST:event_txtSNFocusLost

    private void txtSGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSGFocusLost
        // TODO add your handling code here:
        validInput();
    }//GEN-LAST:event_txtSGFocusLost

    private void txtSEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSEFocusLost
        // TODO add your handling code here:
        validInput();
    }//GEN-LAST:event_txtSEFocusLost

    private void txtPNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPNFocusLost
        // TODO add your handling code here:
        validInput();
    }//GEN-LAST:event_txtPNFocusLost

    private void txtADRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtADRFocusLost
        // TODO add your handling code here:
        validInput();
    }//GEN-LAST:event_txtADRFocusLost

    public boolean validInput(){
        
        if(txtSN.getText().isBlank()|| !txtSN.getText().matches("[a-zA-Z]{3,}"))
        {
            this.errName.setText("Invalid Name");
            return false;
        }
        this.errName.setText("");
        if(txtPN.getText().isBlank()|| !txtPN.getText().matches("\\d{5,}"))
        {
            errPhone.setText("Invalid Phone");
            return false;
        }
        errPhone.setText("");
        if(txtSE.getText().isBlank()|| !txtSE.getText().matches("\\b[A-Z0-9._%-]+@[A-Z0-9.-]+\\.[A-Z]{2,4}\\b"))
        {
            this.errEmail.setText("Invalid Email");
            return false;
        }
        errEmail.setText("");
        if(txtSG.getText().isBlank()|| !txtSG.getText().matches("\\d+"))
        {
            this.errGrade.setText("Invalid Grade");
            return false;
        }
        errGrade.setText("");
        if(txtADR.getText().isBlank()|| !txtADR.getText().matches("[a-zA-Z]{3,}"))
        {
            this.errAdr.setText("Invalid Address");
            return false;
        }
        errAdr.setText("");
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnExit;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel errAdr;
    private javax.swing.JLabel errEmail;
    private javax.swing.JLabel errGrade;
    private javax.swing.JLabel errName;
    private javax.swing.JLabel errPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblADR;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblPN;
    private javax.swing.JLabel lblRN;
    private javax.swing.JLabel lblSG;
    private javax.swing.JLabel lblSG1;
    private javax.swing.JLabel lblSN;
    private javax.swing.JTextField txtADR;
    private javax.swing.JTextField txtPN;
    private javax.swing.JTextField txtRN;
    private javax.swing.JTextField txtSE;
    private javax.swing.JTextField txtSG;
    private javax.swing.JTextField txtSN;
    // End of variables declaration//GEN-END:variables
}
