/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guessnbgui;

import java.util.Random;

/**
 *
 * @author AAHROI
 */
public class nbGuessGUI extends javax.swing.JFrame {

    /**
     * Creates new form nbGuessGUI
     */
    
    public static int rnb ; //used to generate random number
    public static Random r = new Random(); //intialize random generator
    public static int tries; //nb of tries
    public static boolean found; // check if user guess the number
    public static Drawings panel; // used to draw mashnaqa
    public static int x; // user input
    
    public nbGuessGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawMe = new java.awt.Panel();
        nb = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Play = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextPane();
        pAgain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        drawMe.setBackground(new java.awt.Color(204, 255, 204));
        drawMe.setName(""); // NOI18N
        drawMe.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                drawMeComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                drawMeComponentRemoved(evt);
            }
        });
        drawMe.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                drawMeComponentShown(evt);
            }
        });

        javax.swing.GroupLayout drawMeLayout = new javax.swing.GroupLayout(drawMe);
        drawMe.setLayout(drawMeLayout);
        drawMeLayout.setHorizontalGroup(
            drawMeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );
        drawMeLayout.setVerticalGroup(
            drawMeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("You have to guess a number in 7 tries");

        Play.setText("Play");
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter a number between 1 and 100");

        jScrollPane1.setEnabled(false);
        jScrollPane1.setViewportView(result);

        pAgain.setText("Play Again");
        pAgain.setEnabled(false);
        pAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAgainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(nb, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(Play))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(pAgain)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(drawMe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(drawMe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(nb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Play)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(pAgain)))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed
        // TODO add your handling code here:
       
       if(nb.getText().length()>0)
       {
            if(tries>0 && !found)
            {
                tries--;
                System.out.println("Playing :" + tries);
                x = Integer.parseInt(nb.getText());
                if( x == rnb)
                {
                    result.setText("");
                    result.setText("Congratulations, You guess the number in "+ (7-tries) +" try/tries.");
                    found = true;
                    Play.setEnabled(false);
                    pAgain.setEnabled(true);
                }
                else
                {
                    drawMe.removeAll();
                    panel = new Drawings(tries);
                    //panel.setVisible(true);
                    drawMe.add(panel); 
                    drawMe.repaint();
                    drawMe.validate(); 
                    
                    result.setText("");
                   
                    if(x>rnb)
                       result.setText("You need a smaller number,Try Again.\n ");
                    else
                        result.setText("You need a greater number,Try Again.\n");
                    
                     result.setText(result.getText()+ tries + " try/tries left!");
                }
            }
            else if (!found)
            {
                result.setText("");
                result.setText("Sorry you reached the number of tries, Game over. ");
                result.setText(result.getText()+ " \nThe number to guess was "+ rnb + " !");
                Play.setEnabled(false);
                pAgain.setEnabled(true);
            }
        }  
    }//GEN-LAST:event_PlayActionPerformed

    private void pAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAgainActionPerformed
        // TODO add your handling code here:
        
        Play.setEnabled(true);
        pAgain.setEnabled(false);
        
        rnb = r.nextInt(101)+1;
        tries = 7;
        found=false;
        result.setText("");
        nb.setText("");
        nb.setFocusable(true);
        drawMe.removeAll();
        panel = new Drawings(tries);
        
        //panel.setVisible(true);
        drawMe.add(panel); 

        drawMe.repaint();

        drawMe.validate();
        System.out.println("startup :" + tries);
    }//GEN-LAST:event_pAgainActionPerformed

    private void drawMeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_drawMeComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_drawMeComponentShown

    private void drawMeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_drawMeComponentAdded
        // TODO add your handling code here:
   
    }//GEN-LAST:event_drawMeComponentAdded

    private void drawMeComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_drawMeComponentRemoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_drawMeComponentRemoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        rnb = r.nextInt(101)+1;
        tries = 7;
        found=false;
        panel = new Drawings(tries);
        drawMe.removeAll();
        
        //panel.setVisible(true);
        drawMe.add(panel); 
        
        drawMe.repaint();
        
        drawMe.validate();
        System.out.println("startup :" + tries);
        nb.setFocusable(true);
    }//GEN-LAST:event_formWindowOpened

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nbGuessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nbGuessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nbGuessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nbGuessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

     
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new nbGuessGUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Play;
    private java.awt.Panel drawMe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nb;
    private javax.swing.JButton pAgain;
    private javax.swing.JTextPane result;
    // End of variables declaration//GEN-END:variables
}
